# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: WhiteSource@21

    displayName: WhiteSource

    inputs:

      cwd: '$(System.DefaultWorkingDirectory)'

      scanReportTimeout: 45

      configuration: |

        npm.resolveDependencies=false

        npm.includeDevDependencies=false

        npm.runPreStep=false

        nuget.resolveDependencies=false

        nuget.restoreDependencies=false

        nuget.ignoreSourceFiles=true

        nuget.runPreStep=true=false  

        excludes=**/*.tgz
